"use client";
import Head from "next/head";
import Image from "next/image";
import { useEffect, useRef } from "react";
import gsap from "gsap";
import styles from "./AboutMe.module.css";

export default function AboutMe() {
	return (
		<>
			<Head>
				<title>Jasmine Putri | Portfolio</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<main className={`${styles.page}`}>
				<div
					className={`gridContainer ${styles.aboutOuterContainer}`}
					id="about"
				>
					<div style={{ gridColumn: "2 / 5" }}>
						<h2> Hello</h2>
					</div>
				</div>
				<div
					className={`gridContainer ${styles.contactContainer}`}
					id="contact"
				></div>
			</main>
		</>
	);
}
