"use client";
import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import Header from "@/components/Header";
import styles from "../styles/About.module.css";

export default function AboutMe() {
	return (
		<>
			<Head>
				<title>Jasmine Putri | Portfolio</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
            <Header/>
			<main className={`${styles.page}`}>
				<div
					className={`gridContainer ${styles.aboutOuterContainer}`}
					id="about"
				>
					<div
						className={styles.aboutInnerContainer}
						style={{ gridColumn: "1 / 6" }}
					>
						<h2>
							Nice to meet <span>you.</span>
						</h2>
					</div>
					<div style={{ gridColumn: "12/16 " }} className={styles.imgContainer}>
						<Image
							src="/images/logo/baby-me.png"
							alt="Jasmine Putri as a child"
							width={1920}
							height={1080}
							style={{ width: "auto", height: "70%" }}
						/>
					</div>
					<div style={{ gridColumn: "1 / 5" }} className={styles.firstParag}>
						<p>
							I’ve always loved making things—whether it was paper clothes for
							my pencil dolls, sticker packs with double-sided tape, or later,
							customizing Tumblr themes with HTML & CSS. I didn’t realize it
							then, but I was already drawn to design, structure, and how things
							fit together.
						</p>
					</div>
					<div style={{ gridColumn: "6 / 10" }} className={styles.secondParag}>
						<p>
							I studied psychology because I was curious about people—how they
							think, how they make decisions—but I kept coming back to
							designing, building, and problem-solving. When I rediscovered
							coding during COVID, I found UI/UX design, and everything finally
							clicked.
						</p>
					</div>
					<div style={{ gridColumn: "11 / 16" }} className={styles.thirdParag}>
						<p>
							Now, I work as a digital experience designer, creating
							interactive, intuitive, and engaging digital spaces. My work is
							shaped by curiosity, collaboration, and a need to make things feel
							considered—both visually and in how they function. I like figuring
							things out, making connections between ideas, and seeing where
							that leads.
						</p>
					</div>
					<div className={styles.contact} style={{ gridColumn: "span 16" }}>
						<h1>Say hi back!</h1>
						<p>
							Interested in collaborating? Whether it’s a project, an idea, or
							just a good conversation—I'd love to connect!
						</p>
						<div className={styles.contactLinks}>
							<div>
								<b>email:</b> jasmineputridesigns@gmail.com
							</div>
							<div>
								<b>LinkedIn:</b>
								<Link href="https://www.linkedin.com/in/jdputri/">
									/jdputri
								</Link>
							</div>
						</div>
					</div>
				</div>
			</main>
		</>
	);
}
