import Head from "next/head";
import Image from "next/image";
import Header from "@/components/Header";
import Intro from "@/components/Intro";
import ProjectList from "@/components/ProjectList";
import { projectsData } from "@/data/projectsData";
import styles from "@/styles/Home.module.css";

export default function Home() {
  return (
    <>
      <Head>
        <title>Jasmine Putri | Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.page}>
        {/* Sticky Header */}
        <Header />

        {/* Intro Section */}
        <div
          className={`${styles.snapSection} ${styles.introSection}`}
          data-section="intro"
        >
          {/* Gradient Blob */}
          <div className={styles.blobOuterContainer}>
            <div className={styles.blobInnerContainer}>
              <div className={styles.blob}></div>
              <div className={styles.blob}></div>
              <div className={styles.blob}></div>
            </div>
          </div>

          <svg xmlns="http://www.w3.org/2000/svg" style={{ display: "none" }}>
          <filter id="grainyFilter">
            <feTurbulence type="fractalNoise" baseFrequency="1.2" numOctaves="3" stitchTiles="stitch" />
            <feColorMatrix type="saturate" values="0" />
            <feComponentTransfer>
              <feFuncA type="table" tableValues="0 0.1" />
            </feComponentTransfer>
            <feBlend mode="screen" in="SourceGraphic" />
          </filter>
        </svg>

          {/* Intro Content */} 
          <Intro />
          <div className={styles.imgContainer}>
            <Image
              src="/images/logo/logo-solid.svg"
              alt="logo"
              width={462}
              height={516}
              priority
              className={styles.logo}
            />
          </div>
        </div>

        {/* Projects Section */}
        <div className={`${styles.projectsSection}`} data-section="projects">
          <ProjectList projects={projectsData} />
        </div>

        {/* Footer Section */}
        {/* <div
          className={`${styles.snapSection} ${styles.footerSection}`}
          data-section="footer"
        >
          <footer className={styles.footer}>Jasmine Putri </footer>
        </div> */}
      </div>
    </>
  );
}
