"use client";
import Head from "next/head";
import Image from "next/image";
import { useState, useEffect, useRef } from "react";
import Header from "@/components/Header";
import Intro from "@/components/Intro";
import ProjectList from "@/components/ProjectList";
import { projectsData } from "@/data/projectsData";
import styles from "@/styles/Home.module.css";
import gsap from "gsap";
import { useGSAP } from "@gsap/react";
import useMediaQuery from "@/hooks/useMediaQuery";
import AboutMe from "@/components/AboutMe";

export default function Home() {
	const isMobile = useMediaQuery("(max-width: 840px)");
	const projectsRef = useRef(null);
	const [showSectionTitle, setShowSectionTitle] = useState(false);

	useEffect(() => {
		const observer = new IntersectionObserver(
			([entry]) => {
				console.log("Is projectsSection visible?", entry.isIntersecting); // Debugging
				setShowSectionTitle(entry.isIntersecting);
			},
			{
				root: null,
				threshold: 0.1,
			}
		);

		if (projectsRef.current) {
			observer.observe(projectsRef.current);
		}

		return () => {
			if (projectsRef.current) {
				observer.unobserve(projectsRef.current);
			}
		};
	}, []);

	return (
		<>
			<Head>
				<title>Jasmine Putri | Portfolio</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<main className={`${styles.page}`}>
				<section
					className={`${styles.snapSection} ${styles.introSection}`}
					data-section="intro"
				>
					<Intro />
				</section>

				{/* Projects Section */}
				<section
					className={styles.projectsSection}
					gridContainer
					data-section="projects"
				>
					<article className={styles.projectsListContainer}>
						<ProjectList projects={projectsData} />
					</article>
				</section>
				{/* Footer Section */}
				{/* <div
          className={`${styles.snapSection} ${styles.footerSection}`}
          data-section="footer"
        >
          <footer className={styles.footer}>Jasmine Putri </footer>
        </div> */}
			</main>
		</>
	);
}
