"use client";
import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import Header from "@/components/Header";
import styles from "../styles/About.module.css";
import Timeline from "@/components/Timeline";

export default function AboutMe() {
	return (
		<>
			<Head>
				<title>Jasmine Putri | Portfolio</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<Header />
			<main className={`${styles.page}`}>
				<div
					className={`gridContainer ${styles.aboutOuterContainer}`}
					id="about"
				>
					<div style={{ gridColumn: "span 16" }}>
						<Timeline />
					</div>
				</div>
			</main>
		</>
	);
}
