import Head from "next/head";
import Image from "next/image";
import { useState, useEffect, useRef } from "react";
import Header from "@/components/Header";
import useMediaQuery from "@/hooks/useMediaQuery";
import styles from "./styles/Projects.module.css";
import Box from "@/components/Box";
import FeatureBox from "../FeatureBox";


export default function Project() {
  const isMobile = useMediaQuery("(max-width: 840px)");
  const [compactHeader, setCompactHeader] = useState(false);

  return (
    <>
      <Head>
        <title>Jasmine Putri | Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className={styles.page}>
        {/* Sticky Header */}
        <Header compactHeader={compactHeader} className={styles.header}/>

        <main className={styles.mainWrapper}>
          <div className={styles.sideNav}>
            <div className={styles.sideNavMenu}>
              <p>Overview</p>
              <p>Research</p>
              <p>Design</p>
              <p>Development</p>
            </div>
          </div>
          <div className={styles.contentWrapper}>
            {/* Intro Section */}
            <section className={styles.projectSummary}>
              <h2 className={`${styles.projectTitle} name-font-med`}>Neighbourly<span>project</span></h2>
              {/* <p>Helping internationally educated nurses (IENs) practice and prepare for interviews using AI-powered feedback.</p> */}
              <ul>
                <li>Role: UI/UX Designer, Front-end Developer</li>
                <li>Timeline: January 2024 -- May 2024</li>
                <li>Type: Web-app, mobile app</li>
                <li>Tech & Tools: Figma, Next.js </li>
                <li>Link: be-neighbourly.com</li>
              </ul>
            </section>

            {/* Overview Section */}
            <Box 
              title="Overview"
              customStyles={{
                outer: { maxWidth: "40vw", margin: 0, marginTop: "10rem" },
                inner: { textAlign: "left", padding: "0" },
              }}
            >
              <p style={{ marginBottom: "1.5rem" }}>A mobile marketplace app designed to connect individuals within their local communities by enabling them to advertise services they offer.</p>
              <p style={{ marginBottom: "6vw" }}>In today’s fast-paced world, people often feel disconnected from their neighbours, making it difficult to find trusted local help or contribute their own expertise. Neighbourly bridges this gap by creating a space where people can connect meaningfully, exchange skills, and build a stronger, more connected and supportive community. </p>
            </Box>

            <Image
              src='/images/neighbourly/homepage.webp'
              width={785}
              height={636}
              alt="Neighbourly App Homepage"
              style={{ width: "95%", height: "auto"}} 
            />

            {/* Features */}

            <FeatureBox
              title="Key Features"
              features={[
                { heading: "Local Service Listings", description: "Easily browse and offer services within your community, from home repairs and pet sitting to tutoring and wellness sessions." },
                { heading: "Learning & Workshops", description: "Join or host local classes in pottery, yoga, coding, cooking, and more to learn new skills or share your expertise." },
                { heading: "Mentorship Opportunities", description: "Connect with experienced mentors for career guidance, personal development, and skill-building in various fields." }
              ]}
              customStyles={{
                container: { margin: "3rem 0", padding: "3rem 2rem" },
                title: { color: "var(--lavender)", fontSize: "1rem"},
                grid: { gap: "3rem" },
                card: { padding: "1.5rem", backgroundColor: "#f9f9f9", borderRadius: "8px" },
                featureTitle: { fontSize: "1.2rem" },
                featureDescription: { fontSize: "1rem", color: "gray" }
              }}
            />

            <Image
              src='/images/neighbourly/all-services-classes.webp'
              width={785}
              height={636}
              alt="Neighbourly App Homepage"
              style={{ width: "95%", height: "auto",  marginTop: "4rem"}} 
            />

            <FeatureBox
              features={[
                { heading: "Interactive Map", description: "Explore services, workshops, and mentorship opportunities in your area through location-based discovery." },
                { heading: "Multi-Language Support", description: "Access the platform in multiple languages, making it more inclusive for diverse communities." },
              ]}
              customStyles={{
                container: { margin: "5rem 0", padding: "3rem 2rem" },
                grid: { gap: "2rem" },
                card: { padding: "1.5rem", backgroundColor: "#f9f9f9", borderRadius: "8px" },
                featureTitle: { fontSize: "1.2rem" },
                featureDescription: { fontSize: "1rem", color: "gray" }
              }}
            />

            <div style={{display: "flex", flexDir: "row", alignItems: "flex-start", marginTop: "4rem"}}>
              <video 
                src="/images/neighbourly/interactive-map.webm" 
                width="700" 
                height="350" 
                autoPlay 
                loop 
                muted 
                playsInline 
              />
              <video 
                src="/images/neighbourly/language-settings.webm" 
                width="700" 
                height="350" 
                autoPlay 
                loop 
                muted 
                playsInline 
              />
            </div>
            
            <Image
              src='/images/neighbourly/quiz-2.webp'
              width={785}
              height={636}
              alt="Neighbourly App Homepage"
              style={{ width: "95%", height: "auto",  marginTop: "4rem"}} 
            />

            <Box
              customStyles={{
                outer: { 
                  width: "73vw", 
                  height: "70vh", 
                  padding: "0",
                  margin: "0",
                  marginTop: "4rem",
                  backgroundColor: "#FDE0D9", 
                  display: "flex", 
                  justifyContent: "center", 
                  alignItems: "center" 
                },
                inner: { padding: "0" } 
              }}
            >
              <video 
                src="/images/neighbourly/app-walkthrough.webm" 
                autoPlay 
                loop 
                muted 
                playsInline 
                style={{ width: "250px", height: "435px", objectFit: "cover", borderRadius: "12px" }}
              />
            </Box>

            <Image
              src='/images/neighbourly/app-architecture.webp'
              width={785}
              height={636}
              alt="Neighbourly App Homepage"
              style={{ width: "95%", height: "auto",  marginTop: "4rem"}} 
            />

            <Image
              src='/images/neighbourly/colours-typefaces.webp'
              width={785}
              height={636}
              alt="Neighbourly App Homepage"
              style={{ width: "95%", height: "auto",  marginTop: "4rem"}} 
            />


          </div>

          {/* Footer Section */}
        </main>
          <footer className={styles.footer}>Jasmine Putri</footer>
      </div>
    </>
  );
}

export async function getStaticPaths() {
  const projects = ["onward", "fairshare", "bcitma"]; // Add all project slugs

  return {
    paths: projects.map((slug) => ({ params: { onward: slug } })),
    fallback: false, // If user visits an unknown project, show a 404 page
  };
}

export async function getStaticProps({ params }) {
  const projectData = {
    onward: {
      title: "Neighbourly App",
      role: "UI/UX Designer, Developer",
      timeline: "Jan 2024 - May 2024",
      tech: ["Next.js", "Azure Speech"],
      link: "onward-prep.com",
    },
  };

  if (!projectData[params.onward]) {
    return { notFound: true }; // Show 404 if the project doesn't exist
  }

  return { props: { project: projectData[params.onward] } };
}

