import Head from "next/head";
import Image from "next/image";
import useMediaQuery from "@/hooks/useMediaQuery";
import Header from "@/components/Header";
import FeatureBox from "@/components/FeatureBox";
import ProjectSummary from "@/components/ProjectSummary";
import SectionTextBox from "../SectionText";
import FramedBox from "../FramedBox";
import TwoColBox from "../TwoColBox";
import SideNav from "../SideNav";
import styles from "@/styles/Projects.module.css";

export default function Project() {
	const isMobile = useMediaQuery("(max-width: 840px)");

	return (
		<>
			<Head>
				<title>Jasmine Putri | Portfolio</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<div className={styles.page}>
				<Header />

				{/* Floating Side Nav */}
				<SideNav
					className={styles.floatingSideNav}
					sections={[
						{ name: "Overview", id: "overview" },
						{ name: "Commercial", id: "commercial" },
						{ name: "Features", id: "features" },
						{ name: "Design & Branding", id: "design" },
					]}
				/>

				<main className="gridContainer">
					{/* Project Summary */}
					<div
						style={{
							gridColumn: "4 / span 10",
							marginTop: "3rem",
							marginBottom: "8rem",
						}}
					>
						<ProjectSummary
							title="Onward"
							details={[
								{ label: "role", value: "UI/UX Designer, Front-end Developer" },
								{ label: "timeline", value: "January 2024 — May 2024" },
								{ label: "type", value: "Website / Web App / Mobile App" },
								{ label: "toolstack", value: "Figma, Next.js" },
								{ label: "program used", value: "Next.js, Azure" },
								{
									label: "link",
									value: (
										<a
											href="https://be-neighbourly.com"
											target="_blank"
											rel="noopener noreferrer"
										>
											be-neighbourly.com
										</a>
									),
								},
							]}
						/>
					</div>

					{/* Overview Section */}
					<div style={{ gridColumn: "4 / span 10" }} id="overview">
						<SectionTextBox
							title="What is Onward?"
							subtitle="Overview"
							variant="compact"
							customStyles={{ outer: { maxWidth: "1200px" } }}
						>
							<p>
								Onward is a web application designed to help Internationally
								Educated Nurses (IENs) successfully enter the Canadian workforce
								by improving their interview confidence and communication
								skills.
							</p>
							<p>
								Onward was created for the BCIT D3 and FSWD showcase, themed
								around leveraging AI-driven pattern recognition to develop
								solutions for under-represented and disadvantaged communities.
							</p>
						</SectionTextBox>
					</div>
					<div style={{ gridColumn: "2 / span 14", marginTop: "4rem" }}>
						<Image
							src="/images/onward/transcription.png"
							width={785}
							height={636}
							alt="Onward Practice Interview Interface"
							style={{ width: "95%", height: "auto" }}
						/>
					</div>

					{/* Ideation Section */}
					<div style={{ gridColumn: "4 / span 10" }} id="ideation">
						<SectionTextBox
							title="How Can AI-Driven Tools Support Newcomers in Canada?"
							subtitle="Ideation"
							variant="compact"
							customStyles={{
								outer: { maxWidth: "1200px", marginTop: "5rem" },
							}}
						>
							<p>
								The ideation process initially explored a range of challenges
								newcomers face when settling in Canada, from navigating services
								to finding employment. Through this process, employment emerged
								as a critical milestone, with successful employment contributing
								not only to financial security but also to social integration
								and confidence.
							</p>
							<p>
								To narrow the focus, healthcare was identified as a key sector
								where <b>immigrants play a significant role,</b> making up
								approximately{" "}
								<b>
									25% of the workforce in Canada’s health-related occupations{" "}
								</b>
								[1]. This, combined with the ongoing nursing shortage,
								highlighted the importance of supporting internationally
								educated nurses (IENs) in overcoming the language, cultural, and
								communication barriers that often arise during job interviews.
							</p>
						</SectionTextBox>
					</div>
					<div style={{ gridColumn: "2 / span 15", marginTop: "5rem" }}>
						<Image
							src="/images/onward/transcription.png"
							width={785}
							height={636}
							alt="Onward Practice Interview Interface"
							style={{ width: "95%", height: "auto" }}
						/>
					</div>
					<div style={{ gridColumn: "4 / span 10" }} id="research">
						<SectionTextBox
							title="The Problem"
							subtitle="Research"
							variant="compact"
							customStyles={{
								outer: { maxWidth: "1200px", marginTop: "5rem" },
							}}
						>
							<p>
								With immigrants making up 25% of registered nurses in Canada,
								internationally educated nurses (IENs) play a crucial role in
								supporting the country’s healthcare system. Despite their skills
								and experience, many internationally educated professionals
								struggle to find employment that matches their qualifications.
							</p>
              <p>
                In 2021, 26.7% of recent immigrants were employed in positions
								for which they were overqualified, underscoring ongoing
								challenges related to credential recognition, licensing
								requirements, and adapting to Canadian workplace expectations.
              </p>
						</SectionTextBox>
						<FeatureBox
							title="What Barriers do IENs Trying to Enter the Canadian Healthcare Face?"
							features={[
								{ heading: "International credentials being undervalued." },
								{
									heading:
										"Language and cultural challenges affecting interview performance.",
								},
								{
									heading:
										"Performance anxiety and a lack of tailored feedback.",
								},
							]}
							customStyles={{ margin: "0", marginTop: "5rem", padding: "0" }}
						/>
					</div>
					{/* <Box 
              title="Overview"
              customStyles={{
                outer: { maxWidth: "40vw", margin: 0, marginTop: "10rem" },
                inner: { textAlign: "left", padding: "0" },
              }}
            >
              <p style={{ marginBottom: "1.5rem" }}>ONWARD is a web application designed to help Internationally Educated Nurses (IENs) successfully enter the Canadian workforce by improving their interview confidence and communication skills.</p>
              <p style={{ marginBottom: "10vw" }}>Onward was created for the BCIT D3 and FSWD showcase, themed around leveraging AI-driven pattern recognition to develop solutions for under-represented and disadvantaged communities.</p>
            </Box>

            <Image
              src='/images/onward/transcription.png'
              width={785}
              height={636}
              alt="Onward Practice Interview Interface"
              style={{ width: "95%", height: "auto"}} 
            /> */}

					{/* Research Section */}
					{/* <Box
              subtitle="Research"
              title="The Problem"
              customStyles={{
                outer: { maxWidth: "40vw", margin: 0, marginTop: "12rem" },
                inner: { textAlign: "left", padding: "0" },
              }}
            >
              <p>Canada’s healthcare system faces a severe nursing shortage, but IENs struggle to secure roles that match their skills (1, 2).</p>
              <p>Only 26.2% of internationally educated immigrants in Ontario were employed in jobs matching their skill level, meaning approximately 73.8% were underemployed. </p>
            </Box> */}
				</main>
				<footer className={styles.footer}>Jasmine Putri</footer>
			</div>
		</>
	);
}

export async function getStaticPaths() {
	const projects = ["onward", "fairshare", "bcitma"]; // Add all project slugs

	return {
		paths: projects.map((slug) => ({ params: { onward: slug } })),
		fallback: false, // If user visits an unknown project, show a 404 page
	};
}

export async function getStaticProps({ params }) {
	const projectData = {
		onward: {
			title: "Onward Case Study",
			role: "Developer, User Research",
			timeline: "Sept 2024 - Dec 2024",
			tech: ["Next.js", "Azure Speech"],
			link: "onward-prep.com",
		},
	};

	if (!projectData[params.onward]) {
		return { notFound: true }; // Show 404 if the project doesn't exist
	}

	return { props: { project: projectData[params.onward] } };
}
