import Head from "next/head";
import Image from "next/image";
import useMediaQuery from "@/hooks/useMediaQuery";
import Header from "@/components/Header";
import FeatureBox from "@/components/FeatureBox";
import ProjectSummary from "@/components/ProjectSummary";
import SectionTextBox from "../SectionText";
import FramedBox from "../FramedBox";
import ResponsiveSection from "../ResponsiveSection";
import TwoColBox from "../TwoColBox";
import SideNav from "../SideNav";
import styles from "@/styles/Projects.module.css";
import FlipCard from "../FlipCard";
import FullWidth from "../FullWidth";

export default function Project() {
	const isMobile = useMediaQuery("(max-width: 840px)");

	const handleLearnMore = (title) => {
		console.log(`Learn more clicked for: ${title}`);
		// You can implement routing or modals for more information
	};

	return (
		<>
			<Head>
				<title>Jasmine Putri | Portfolio | Onward</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<div className={styles.page}>
				<Header />

				{/* Floating Side Nav */}
				<SideNav
					className={styles.floatingSideNav}
					sections={[
						{ name: "Overview", id: "overview" },
						{ name: "Commercial", id: "commercial" },
						{ name: "Features", id: "features" },
						{ name: "Design & Branding", id: "design" },
					]}
				/>

				<main className="gridContainer">
					{/* Project Summary */}
					<div
						style={{
							gridColumn: "4 / span 10",
							marginTop: "3rem",
							marginBottom: "5rem",
						}}
					>
						<ProjectSummary
							style={{
								marginBottom: "0",
								paddingBottom: "0",
							}}
							title="Onward"
							details={[
								{ label: "role", value: "UI/UX Designer, Front-end Developer" },
								{ label: "timeline", value: "January 2024 — May 2024" },
								{ label: "type", value: "Website / Web App / Mobile App" },
								{ label: "toolstack", value: "Figma, Next.js" },
								{ label: "program used", value: "Next.js, Azure" },
								{
									label: "link",
									value: (
										<a
											href="https://be-neighbourly.com"
											target="_blank"
											rel="noopener noreferrer"
										>
											be-neighbourly.com
										</a>
									),
								},
							]}
						/>
					</div>

					{/* Overview Section */}
					<div
						style={{ gridColumn: "4 / span 10", marginTop: "0" }}
						id="overview"
					>
						<SectionTextBox
							title="What is Onward?"
							subtitle="Overview"
							variant="compact"
							customStyles={{ outer: { maxWidth: "1200px" } }}
						>
							<p>
								Onward is a web application designed to help Internationally
								Educated Nurses (IENs) successfully enter the Canadian workforce
								by improving their interview confidence and communication
								skills.
							</p>
							<p>
								Onward was created for the BCIT D3 and FSWD showcase, themed
								around leveraging AI-driven pattern recognition to develop
								solutions for under-represented and disadvantaged communities.
							</p>
						</SectionTextBox>
					</div>
					<div style={{ gridColumn: "2 / span 15", marginTop: "0" }}>
						<Image
							src="/images/onward/transcription.png"
							width={785}
							height={636}
							alt="Onward Practice Interview Interface"
							style={{ width: "95%", height: "auto" }}
						/>
					</div>

					{/* Ideation Section */}
					<div style={{ gridColumn: "4 / span 10 " }} id="ideation">
						<SectionTextBox
							title="How Can AI-Driven Tools Support Newcomers in Canada?"
							subtitle="Ideation"
							variant="compact"
							customStyles={{
								outer: {
									maxWidth: "1200px",
									marginTop: "8rem",
								},
							}}
						>
							<p>
								The ideation process initially explored a range of challenges
								newcomers face when settling in Canada, from navigating services
								to finding employment. Through this process, employment emerged
								as a critical milestone, with successful employment contributing
								not only to financial security but also to social integration
								and confidence.
							</p>
							<p>
								To narrow the focus, healthcare was identified as a key sector
								where <b>immigrants play a significant role,</b> making up
								approximately{" "}
								<b>
									25% of the workforce in Canada’s health-related occupations{" "}
								</b>
								[1]. This, combined with the ongoing nursing shortage,
								highlighted the importance of supporting internationally
								educated nurses (IENs) in overcoming the language, cultural, and
								communication barriers that often arise during job interviews.
							</p>
						</SectionTextBox>
					</div>
					<div style={{ gridColumn: "4 / span 10" }} id="research">
						<SectionTextBox
							title="The Problem"
							subtitle="Research"
							variant="compact"
							customStyles={{
								outer: {
									maxWidth: "1200px",
									marginTop: "8rem",
									marginBottom: "8rem",
								},
							}}
						>
							<p>
								With immigrants making up 25% of registered nurses in Canada,
								internationally educated nurses (IENs) play a crucial role in
								supporting the country’s healthcare system. Despite their skills
								and experience, <b>many internationally educated professionals
								struggle to find employment that matches their qualifications.</b>
							</p>
							<p>
								In 2021, 26.7% of recent immigrants were employed in positions
								for which they were overqualified, underscoring ongoing
								challenges related to credential recognition, licensing
								requirements, and adapting to Canadian workplace expectations.
							</p>
						</SectionTextBox>
						<div
							style={{
								display: "grid",
								padding: "1rem 0",
								color: "var(--violet)",
								// justifyContent: 'center',
								// alignItems: 'center'
							}}
						>
							<h2>
								What Barriers do IENs Trying to Enter the Canadian Healthcare
								Face?
							</h2>
						</div>

						<div
							style={{
								display: "grid",
								gridTemplateColumns: isMobile ? "1fr" : "1fr 1fr 1fr",
								gap: "16px",
							}}
						>
							<FlipCard
								title="Credential Recognition & Licensing"
								description="Many IENs face lengthy and expensive processes to have their qualifications recognized in Canada. These often include extra exams, bridging programs, and courses to meet provincial licensing requirements. This leads to underemployment and long delays in returning to their profession [3] [4]."
								buttonText="Learn More"
								onButtonClick={() =>
									handleLearnMore("Credential Recognition & Licensing")
								}
								customStyles={{ outer: { margin: "8px" } }}
							/>

							<FlipCard
								title="Cultural & Communication Barriers"
								description="Canadian healthcare interviews emphasize soft skills, cultural competency, and familiarity with local healthcare practices. IENs often find these expectations challenging due to unfamiliar formats, different terminology, and cultural differences in how professional experiences are presented [3] [5]."
								buttonText="Learn More"
								onButtonClick={() =>
									handleLearnMore("Cultural & Communication Barriers")
								}
								customStyles={{ outer: { margin: "8px" } }}
							/>

							<FlipCard
								title="Performance Anxiety & Feedback Gaps"
								description="For many IENs, interview anxiety is heightened by unfamiliar hiring practices and a lack of culturally relevant preparation. Canadian employers expect candidates to use the STAR method — often unfamiliar to IENs. Without tailored feedback and practice, they struggle to communicate their skills, impacting confidence and performance [5] [6]."
								buttonText="Learn More"
								onButtonClick={() =>
									handleLearnMore("Performance Anxiety & Feedback Gaps")
								}
								customStyles={{ outer: { margin: "8px" } }}
							/>
						</div>

						{/* GOVT EFFORT  */}
						{/* <SectionTextBox
							title="Existing Government Efforts"
							variant="compact"
							customStyles={{
								outer: { maxWidth: "1200px" },
							}}
						>
							<p>
								Programs like the Foreign Credential Recognition Program aim to
								reduce barriers by funding projects that streamline the
								credential recognition process and improve access to bridging
								programs and mentorship[4].
							</p>
							<p>
								However, these initiatives often focus on licensing, leaving
								interview preparation and confidence-building largely
								unaddressed.
							</p>
						</SectionTextBox> */}

						<SectionTextBox
							title="Survey Insights"
							variant="compact"
							customStyles={{
								outer: {
									maxWidth: "1200px",
									marginTop: "10rem",
									marginBottom: "0",
								},
							}}
						>
							<p>
								To better understand the unique challenges in job interviews,
								surveys of internationally educated and local nurses explored
								how communication, credentials, and preparation affect
								performance.
							</p>
						</SectionTextBox>
					</div>
				</main>
				<FullWidth style={{ background: "var(--vanilla)" }}>
					<ResponsiveSection
						desktopStyle={{ gridColumn: "span 16" }}
						mobileVariant="stacked"
					>
						<FramedBox outerBg="var(--vanilla)" innerBg="transparent">
							<div className="gridContainer">
								<div
									style={{
										display: "grid",
										gap: "2rem",
										gridColumn: "span 16",
									}}
								>
									<FeatureBox
										title="Common Challenges"
										variant="columnLayout"
										features={[
											{
												heading: "Anxiety & Nerves",
												description:
													"Both IENs and local nurses feel nervous, especially when underprepared.",
											},
											{
												heading: "Limited Preparation",
												description:
													"Many nurses struggle to find time and effective ways to prepare.",
											},
											{
												heading: "Critical Thinking Under Pressure",
												description:
													"On-the-spot thinking during behavioural questions is difficult for both groups.",
											},
										]}
										backgroundColors={[
											"var(--grey)",
											"var(--grey)",
											"var(--grey)",
										]}
									/>
									<FeatureBox
										title="Unique IEN Challenges"
										features={[
											{
												heading: "Recognition of Experience & Credentials",
												description:
													"IENs feel their international qualifications are undervalued during interviews.",
											},
											{
												heading: "Language & Terminology Barriers",
												description:
													"IENs often struggle with unfamiliar phrases and terminology, adding stress.",
											},
											{
												heading: "Cultural & Style Differences",
												description:
													"IENs find it difficult to match Canadian expectations for self-promotion and structured responses.",
											},
											{
												heading: "Confidence & Self-Presentation",
												description:
													"Cultural norms around modesty make it harder for IENs to confidently promote themselves.",
											},
										]}
										backgroundColors={[
											"var(--light-lavender)",
											"var(--light-lavender)",
											"var(--light-lavender)",
											"var(--light-lavender)",
										]}
									/>
								</div>
							</div>
						</FramedBox>
					</ResponsiveSection>
				</FullWidth>
				<main className="gridContainer">
					{/* SOLUTION */}
					<div style={{ gridColumn: "4 / span 10" }} id="solution">
						<SectionTextBox
							title="Personalized Interview Coaching"
							subtitle="Solution"
							variant="compact"
							customStyles={{
								outer: {
									maxWidth: "1200px",
									marginTop: "8rem",
									marginBottom: "8rem",
								},
							}}
						>
							<p>
								By tailoring practice sessions and feedback to each user’s
								background, ONWARD helps IENs build the skills, confidence, and
								cultural awareness needed to succeed in interviews — ultimately
								bridging the gap between their experience and what Canadian
								employers expect.
							</p>
						</SectionTextBox>
					</div>

					<div
						style={{
							gridColumn: "2 / span 15",
							marginTop: "0rem",
							marginBottom: "5rem",
						}}
					>
						<Image
							src="/images/onward/transcription.png"
							width={785}
							height={636}
							alt="Onward Practice Interview Interface"
							style={{ width: "95%", height: "auto" }}
						/>
					</div>

					{/* PERSONA & COMPETITIVE ANALYSIS */}
					<div style={{ gridColumn: "span 16" }} id="persona-competitor">
						<SectionTextBox
							title="User Persona"
							variant="compact"
							customStyles={{ outer: { maxWidth: "1200px" } }}
						></SectionTextBox>
						<TwoColBox
							variant="5050"
							align="center"
							justify="center"
							customStyles={{}}
							leftContent={
								<img
									src="/images/onward/persona-1.png"
									style={{ width: "100%", maxWidth: "50vw" }}
								/>
							}
							rightContent={
								<img
									src="/images/onward/persona-2.png"
									style={{ width: "100%", maxWidth: "50vw" }}
								/>
							}
						/>
					</div>
					<div style={{ gridColumn: "4 / span 10" }} id="overview">
						<SectionTextBox
							title="Competitive Analysis"
							subtitle="Overview"
							variant="compact"
							customStyles={{
								outer: {
									maxWidth: "1200px",
									marginTop: "10rem",
									marginBottom: "10rem",
								},
							}}
						>
							<p>
								Onward is a web application designed to help Internationally
								Educated Nurses (IENs) successfully enter the Canadian workforce
								by improving their interview confidence and communication
								skills.
							</p>
							<p>
								Onward was created for the BCIT D3 and FSWD showcase, themed
								around leveraging AI-driven pattern recognition to develop
								solutions for under-represented and disadvantaged communities.
							</p>
						</SectionTextBox>
					</div>

					{/* DEVELOPMENT SECTION */}
					<div style={{ gridColumn: "4 / span 10" }} id="development">
						<SectionTextBox
							title="Toolstack"
							subtitle="Development"
							variant="compact"
							customStyles={{
								outer: {
									maxWidth: "1200px",
									marginTop: "5rem",
									marginBottom: "5rem",
								},
							}}
						>
							<p>
								The ONWARD app was developed using Next.js and React for a
								dynamic and scalable front-end, while Supabase handled backend
								storage and authentication. Chakra UI was chosen for its modular
								design system to ensure accessible and responsive UI components.
							</p>
							<p>
								Onward was created for the BCIT D3 and FSWD showcase, themed
								around leveraging AI-driven pattern recognition to develop
								solutions for under-represented and disadvantaged communities.
							</p>
						</SectionTextBox>
					</div>
				</main>
				<footer className={styles.footer}>Jasmine Putri</footer>
			</div>
		</>
	);
}

export async function getStaticPaths() {
	const projects = ["onward", "fairshare", "bcitma"]; // Add all project slugs

	return {
		paths: projects.map((slug) => ({ params: { onward: slug } })),
		fallback: false,
	};
}

export async function getStaticProps({ params }) {
	const projectData = {
		onward: {
			title: "Onward Case Study",
			role: "Developer, User Research",
			timeline: "Sept 2024 - Dec 2024",
			tech: ["Next.js", "Azure Speech"],
			link: "onward-prep.com",
		},
	};

	if (!projectData[params.onward]) {
		return { notFound: true };
	}

	return { props: { project: projectData[params.onward] } };
}
